### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [jsgiraldoh/config-server-aforo255#1]
Hi,<br><br>url : https://github.com/jsgiraldoh/config-server-aforo255/blob/d28a43168c7fd2204eb8c2f3be5d33214027ab47/micro-deposit-prod.properties <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by jsgiraldoh** [comment]
Hi, 

Hello mate,

Thank you very much for being aware.

I have the files like this because it is a public configuration of a course that I was doing, also when I finish turn off the databases.

Thank you very much for being aware,

Cheers

Toast! @shaybenb

**Comment by shaybenb** [comment]
Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.paypal.com/paypalme/bugbounty1/150USD
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕
